### ISSUE TITLE
抱歉，不知如何给你留言，只好开个issue

### ISSUE THREAD

**Issue by conanwhf** [linghuazaii/blog#1]
你的那篇“服务器节省内存4.5G”的文章里，我认为你的解决方式稍有不妥。标准库的本意是：if len(s2)<n then s1=s2+'0000...'，这是合理的。之所以会出问题，关键是strncpy()给的参数不对。我建议把：
`strncpy(article_item.content, ROW[i], MAX_CONTENT_LEN)`修改成：
`strncpy(article_item.content, ROW[i], strnlen (ROW[i], MAX_CONTENT_LEN))`
你的修改逻辑上没有问题，只是一方面跑的语句更多，速度会受到影响；另一方面没有做标准库的各种error handle和多线程的考虑，可能会有一定的安全问题（这一点我只是假设，并无具体例子）。
一点浅见，望指正。

**Comment by linghuazaii** [comment]
@conanwhf 非常不错的提议，Thank you！:-)
